name: Allocate Flycast IP

on:
  workflow_dispatch:

jobs:
  allocate:
    runs-on: ubuntu-latest

    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl ips allocate-v6 --private -a YOUR_INTERVALS_APP_NAME
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
